# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 03:14
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object2book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(default=booking.models.Booking.pnr, max_length=6, unique=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('objectToBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object2book.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('personId', models.CharField(max_length=12)),
                ('phonenumber', models.CharField(max_length=18, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Person'),
        ),
    ]
