# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:47
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170717_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(default=booking.models.Booking.pnr, max_length=6, unique=True),
        ),
    ]
