# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('object2book', '0005_auto_20170708_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='object2book.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=places.fields.PlacesField(blank=True, max_length=255),
        ),
    ]
