# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object2book', '0008_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
